// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy8-DF3pms6GabT_rUcfEy2KRhkQkIeh0',
    appId: '1:453672797050:android:428c486ce4b20d9e68ccc3',
    messagingSenderId: '453672797050',
    projectId: 'counselor-941b4',
    storageBucket: 'counselor-941b4.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_qJSjguqgyPlr3mH-b-eVMrhAjjfPNKs',
    appId: '1:298688163473:web:85c87c15206766b6135930',
    messagingSenderId: '298688163473',
    projectId: 'virtual-counselor-c2101',
    authDomain: 'virtual-counselor-c2101.firebaseapp.com',
    storageBucket: 'virtual-counselor-c2101.appspot.com',
    measurementId: 'G-HY8EW5Y9ZV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCreULNw8mI6nllfA-zqsnsS5OUUP0x5gk',
    appId: '1:298688163473:ios:a349cd944df4dfb4135930',
    messagingSenderId: '298688163473',
    projectId: 'virtual-counselor-c2101',
    storageBucket: 'virtual-counselor-c2101.appspot.com',
    iosBundleId: 'com.lehigh.edu.counselor',
  );

}